<?php 

$url = $this->getUrl('faq/request/submit');


?>

<h1>FAQ Request</h1>

<form id="request_form" method="post" action="<?php echo $url ?>">
		
		<div class="form_description">
			<h2>Submit your FAQ request here...</h2>
		</div>						
		
		<ul >
			
			<li id="name" >
			<label class="description" for="name">Your Name </label>
			<div>
				<input id="name" name="name" type="text" maxlength="255" value=""/> 
			</div><p class="guidelines" id="guide_1"><small>Enter your full name.</small></p> 
			</li>
			
			<li id="email" >
			<label class="email" for="email">Your Email Address </label>
			<div>
				<input id="email" name="email" type="text" maxlength="255" value=""/> 
			</div><p class="guidelines" id="guide_1"><small>Enter your email address.</small></p> 
			</li>	
			
			<li id="question" >
			<label class="description" for="questiontext">What question would you like answered? </label>
			<div>
				<textarea id="questiontext" name="question"></textarea> 
			</div><p class="guidelines" id="guide_2"><small>Here enter the question you would like to be added to the FAQ.</small></p> 
			</li>
				
			<li class="buttons">
					<input id="saveForm" type="submit" name="submit" value="Submit" />
			</li>
		</ul>
</form>	